databases:
  - name: andra
    plan: free
    databaseName: db
    user: yvangodimomo

services:
  - type: web
    plan: free
    name: andra
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m uvicorn salon.asgi:application --host 0.0.0.0 --port 8000"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4